DROP TABLE IF EXISTS games CASCADE;
CREATE TABLE games(
  id SERIAL PRIMARY KEY NOT NULL,
  season VARCHAR(255) NOT NULL,
  week INTEGER NOT NULL,
  game INTEGER NOT NULL,
  opponent VARCHAR(255) NOT NULL
);
