export const performanceState = {
  game_id: "",
  player_id: "",
  hitting_kills: 0,
  hitting_errors: 0,
  hitting_oks: 0,
  blocking_successfuls: 0,
  blocking_touches: 0,
  blocking_errors: 0,
  blocking_oks: 0,
  passing_3: 0,
  passing_2: 0,
  passing_1: 0,
  passing_0: 0,
  serving_aces: 0,
  serving_errors: 0,
  serving_oks: 0,
  digging_successfuls: 0,
  digging_touches: 0,
  digging_misses: 0,
  setting_assists: 0,
  setting_oks: 0,
  setting_errors: 0
}